name       : perl-text-patch
version    : 1.8
release    : 5
source     :
    - https://cpan.metacpan.org/authors/id/C/CA/CADE/Text-Patch-1.8.tar.gz : eaf18e61ba6a3e143846a7cc66f08ce58a0c4fbda92acb31aede25cb3b5c3dcc
license    : GPL-2.0-or-later
component  : programming.perl
summary    : Patches text with given patch
description: |
    Text::Patch combines source text with given diff (difference) data. Diff data is produced by Text::Diff module or by the standard diff utility (man diff, see -u option)
builddeps  :
    - perl-text-diff    # check
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
check      : |
    %make test
